name: Test USB Cleaner

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Bats
        run: sudo apt-get update && sudo apt-get install -y bats
      - name: Run Bats tests
        run: bats tests/cleaner.bats
